
spring:
  application:
    name: PROD-GLOBAL-CONFIG-SERVER
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9999/eureka
